### ISSUE TITLE
Update Team Charter and Create Developer Onboarding Presentation

### ISSUE THREAD

**Issue by STG5326** [azurenoops/ref-scca-enclave-landing-zone-starter#34] opened 2023-08-03 20:18 UTC
Matt Ross to update the charter. Schedule a one-hour call with Spins and SSJ for next Thursday August 10th.

**Comment by matross-gh** [comment] 2023-08-03 20:25
Update the charter on the team's decision about branch naming using scaled trunk-based development.

**Comment by sstjean** [comment] 2023-08-04 16:47
Is this Issue a duplicate of https://github.com/orgs/azurenoops/projects/1?pane=issue&itemId=35011848 ?

**Comment by jrspinella** [comment] 2023-11-21 15:58
This is a dup, closing

**Closed by jrspinella** 2023-11-21 15:58 UTC
Labels: documentation
