### ISSUE TITLE
TEST CASE - Deploy LZ Starter to a single subscription.

### ISSUE THREAD

**Issue by jrspinella** [azurenoops/ref-scca-enclave-landing-zone-starter#36] opened 2023-08-13 14:11 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
This issue is a test case that needs to be done for the landing zone starter. Follow the test steps below.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] test case
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Test steps 
>
1.  Clone repo
2.  

### Mention any other details that might be useful

> ---------------------------------------------------------------

**Comment by timothymeyers** [comment] 2023-08-16 16:14
This is a duplicate of #38 and #40

**Closed by timothymeyers** 2023-08-16 16:14 UTC
Labels: good first issue
